### ISSUE TITLE
[Tracker] kernel stable checklist

### ISSUE THREAD

**Issue by nE0sIghT** [nE0sIghT/android_kernel_xiaomi_msm8953#7]
- [x] Overall display
  - [x] dsi panels
    - [x] nt35532
    - [x] nt35596
    - [x] nt35596-tianma
    - [x] otm1911
    - [x] r63350
    - [x] ili9885
  - [ ] touchscreens
    - [x] ft5435
    - [ ] ist3038c
    - [ ] gt9xx mido specific driver
  - [x] [framebuffer](https://github.com/nE0sIghT/android_kernel_xiaomi_msm8953/issues/1)
  - [x] [kgsl](https://github.com/nE0sIghT/android_kernel_xiaomi_msm8953/issues/5)
  - [x] video decoding
- [x] Overall audio
  - [x] bluetooth audio
  - [x] choppy crack fixed
  - [x] FM
  - [x] headset
  - [x] mic
  - [x] phone call
  - [x] speaker
- [x] bluetooth
- [ ] camera
- [x] charge
- [x] data encryption
- [x] Fingerprint
  - [x] goodix
  - [x] [fpc](https://github.com/nE0sIghT/android_kernel_xiaomi_msm8953/issues/18)
- [x] GPS
- [x] led
- [x] lirc
- [x] modem
  - [x] sim1
  - [x] sim2
  - [x] HSPA
  - [x] LTE
- [x] USB
- [x] wifi
  - [x] 2.4 GHz
  - [x] 5 GHz
  - [x] hotspot

**Comment by offset1313** [comment]
Mido  have ft5435 not ft5346
goodix  and nt35596-tianma working

**Comment by nE0sIghT** [comment]
Changed, thanks

**Comment by offset1313** [comment]
still a typo there
it's  ft5435

**Comment by nE0sIghT** [comment]
> still a typo there

Changed again.

I wonder if there are mido versions with all those dsi panels...
Looks like two main are nt35532 and nt35596-tianma.

**Comment by tanz3** [comment]
Audio , Goodix and Camera doesn‘t work on MIUI pie

**Comment by offset1313** [comment]
YEAH THERE ARE people with different panels.
i have confirmed nt35596-tianma which my device have 
there is group on telegram for mido having 9000+ members there we might get testers with different panels.
https://tgram.io/group/740/rn4official

**Comment by nE0sIghT** [comment]
> Camera

Unfortunatelly, this is completelly out of my scope since my phone is cameraless (work restricted).
Someone should take care of it.

**Comment by Nicklas373** [comment]
Display otm1911 working perfectly here, just a bit delay sometimes when wakeup
Video decoding isn't working, vidc error with something '_'
Audio is broken for me, at initial, kernel failed to detect any soundcard. Is that from techpack?
Camera stack not work
Fingerprint work here (goodix)
And also external storage can't be mounted.

I'll try to fix something if i can from that list, that's my report. And thanks to your hard work sir!!

**Comment by nE0sIghT** [comment]
> Fingerprint work here (goodix)

Looks like it broken on some devices including mine.

**Comment by offset1313** [comment]
yeah fingerprint goodix working fine on android 10 confirmed
also panel  r63350-ebbg confirmed working

**Comment by Nicklas373** [comment]
> > Fingerprint work here (goodix)
> 
> Looks like it broken on some devices including mine.

[ 3356.823335] goodix_fp soc:goodix_fp: Selected 'goodixfp_reset_reset'
[ 3356.826375] goodix_fp soc:goodix_fp: Selected 'goodixfp_reset_active'
[ 3356.830174] IRQ has been enabled.
[ 3356.845453] goodix_fp soc:goodix_fp: Selected 'goodixfp_reset_reset'
[ 3356.848511] goodix_fp soc:goodix_fp: Selected 'goodixfp_reset_active'
[ 3356.865169] IRQ has been enabled.
[ 3356.940955] goodix_fp soc:goodix_fp: Selected 'goodixfp_reset_reset'
[ 3356.943989] goodix_fp soc:goodix_fp: Selected 'goodixfp_reset_active'
[ 3356.963511] IRQ has been enabled.

Goodix reset seems fine here, don't know why

**Comment by Roker2** [comment]
RIL is working
![IMG_20200421_174758_051](https://user-images.githubusercontent.com/25015209/79880110-3b67ae00-83f8-11ea-88af-a204cd14a924.jpg)

**Comment by Roker2** [comment]
USB doesn't work.

**Comment by Roker2** [comment]
My logcat
https://gist.github.com/Roker2/6ad24eb61610066444f83c3217a35671

**Comment by Nicklas373** [comment]
> My logcat
> https://gist.github.com/Roker2/6ad24eb61610066444f83c3217a35671

can you share dmesg or last_kmsg too here?

**Comment by offset1313** [comment]
> USB doesn't work.

Confirmed

**Comment by nE0sIghT** [comment]
For USB to work there is should be support from OS.
Look for my comment https://github.com/nE0sIghT/android_kernel_xiaomi_msm8953/issues/5#issuecomment-615579540 - actually about ```init.msm.usb.configfs.rc```.

**Comment by AryanKedare** [comment]
just incase

https://github.com/AryanKedare/device_xiaomi_mido-4.9

also @Roker2 

https://github.com/AryanKedare/device_xiaomi_mido-4.9/commit/a07a6d1edd946c5d97cb7df774aa8c1780159a5b

**Comment by AryanKedare** [comment]
@nE0sIghT seems like goodix is working ill try to fix fpc 

i guess wifi also works fine so you can tick that


My Build has audio camera and volte calls make device reboot issue

![photo_2020-04-21_22-23-49](https://user-images.githubusercontent.com/18442378/79894846-abd7f480-8423-11ea-896e-2cf1264c258f.jpg)

**Comment by nE0sIghT** [comment]
> seems like goodix is working

I unsure with it for now. It not works for me, but others reported it works.  
I now using insecure build with permissive selinux - maybe this is root cause...

**Comment by AryanKedare** [comment]
> > seems like goodix is working
> 
> I unsure with it for now. It not works for me, but others reported it works.
> I now using insecure build with permissive selinux - maybe this is root cause...

even my build is permissive

**Comment by AryanKedare** [comment]
just for reference 
https://github.com/nichcream

**Comment by Roker2** [comment]
> > My logcat
> > https://gist.github.com/Roker2/6ad24eb61610066444f83c3217a35671
> 
> can you share dmesg or last_kmsg too here?

Now - no, I can later

**Comment by Roker2** [comment]
> @nE0sIghT seems like goodix is working ill try to fix fpc
> 
> i guess wifi also works fine so you can tick that
> 
> My Build has audio camera and volte calls make device reboot issue
> 
> ![photo_2020-04-21_22-23-49](https://user-images.githubusercontent.com/18442378/79894846-abd7f480-8423-11ea-896e-2cf1264c258f.jpg)

Oh, yes, I got reboot too. But I thought, that to need to stop experiment and to restore backup.

**Comment by offset1313** [comment]
ili9885-boe panel also working properly

**Comment by offset1313** [comment]
As you have checked it ! Is goodix working for you @nE0sIghT if not try android 10 based rom!

**Comment by nE0sIghT** [comment]
> is goodix working for you

No. I checked it based on others input.

**Comment by usmanmughalji** [comment]
You can also try to restore persist @nE0sIghT maybe this fix goodix for you because sometimes doing testing or experimentation can breaks stuff.

**Comment by offset1313** [comment]
What problem are you facing exact with goodix ?
Aren't you able to enroll it?
@nE0sIghT

**Comment by herobuxx** [comment]
Charge, video, and notification LED works. But it play video w/o audio

**Comment by offset1313** [comment]
Yeah charger okk notification led okk video okk

But no audio

**Comment by offset1313** [comment]
These are device tree from 3.18 and 4.9
Diff between them using any interactive diff tool.
While I am trying to figure out changes if someone else also is also intersted then files are shared here.

https://github.com/offset1313/misc

**Comment by offset1313** [comment]
So here full device tree source file from 3.18 and 4.9 version would be shared.
Anyone could use it for diff and find out any significant changes in nodes.

https://github.com/offset1313/misc

**Comment by nE0sIghT** [comment]
To get sorted diff between dtb one can use ```dtc``` tool to decompile dtb to dts and ```dtx``` tool to create sorted diff.
Both tools are bundled with kernel.

**Comment by offset1313** [comment]
That is what exact done  there for ease of others

**Comment by offset1313** [comment]
> To get sorted diff between dtb one can use ```dtc``` tool to decompile dtb to dts and ```dtx``` tool to create sorted diff.
> Both tools are bundled with kernel.

Gotcha! Okk

**Comment by offset1313** [comment]
If someone is interested in sorted diff.
Between dts then it is here :

https://github.com/offset1313/misc/blob/master/diff_sorted

**Comment by offset1313** [comment]
New :

adsp_shmem_device_region@0xc0100000 
mem_dump_region
qseecom_ta_region
	i2c@78b5000
nq@28 
kgsl_iommu_test_device0
wsa881x_analog_vi_pctrl

Removed : 

 venus_qseecom_region@0 
adv7533@39
wsa881x-i2c-codec@44 
wsa881x-i2c-codec@e
List is not complete

And many more changes!!!

**Comment by Nicklas373** [comment]
> New :
> 
> adsp_shmem_device_region@0xc0100000
> mem_dump_region
> qseecom_ta_region
> i2c@78b5000
> nq@28
> kgsl_iommu_test_device0
> wsa881x_analog_vi_pctrl
> 
> Removed :
> 
> venus_qseecom_region@0
> adv7533@39
> wsa881x-i2c-codec@44
> wsa881x-i2c-codec@e
> List is not complete
> 
> And many more changes!!!

Just think we need that venus node for video decoding, since we rely on that think in kernel when video decode, also, vidc got several error when play video

**Comment by nE0sIghT** [comment]
> Just think we need that venus node for video decoding

No. It's not used anymore. Instead it's handled via new iommu.

@ all
You should not think dts must be 100% same.
Many relations where changed.

**Comment by offset1313** [comment]
> @nE0sIghT seems like goodix is working ill try to fix fpc
> 
> i guess wifi also works fine so you can tick that
> 
> My Build has audio camera and volte calls make device reboot issue
> 
With the audio fix the call reboot issue doesn't exist anymore atleast as I have tested @AryanKedare

**Comment by Nicklas373** [comment]
> > @nE0sIghT seems like goodix is working ill try to fix fpc
> > i guess wifi also works fine so you can tick that
> > My Build has audio camera and volte calls make device reboot issue
> 
> With the audio fix the call reboot issue doesn't exist anymore atleast as I have tested

Good then

**Comment by offset1313** [comment]
nt35596 tested working  properly

**Comment by Roker2** [comment]
Add please info about GPS and Bluetooth.

Добавьте пожалуйста информацию о GPS и Bluetooth.

**Comment by ZjemCiKolege** [comment]
I connected bluetooth speaker(no sound) and dualshock 4 works :)

**Comment by Nicklas373** [comment]
@Roker2 gps and bluetooth worked

**Comment by Nicklas373** [comment]
@ZjemCiKolege still not test for bluetooth audio transmission so far '_'

**Comment by Nicklas373** [comment]
Sir @nE0sighT, is external sdcard work on you?

**Comment by AryanKedare** [comment]
Okay i have hex edited fp blobs to make fpc work ill post a build soon and need to test sdcard

**Comment by offset1313** [comment]
> Okay i have hex edited fp blobs to make fpc work ill post a build soon and need to test sdcard

Do you need better reverse engineering tool??

**Comment by offset1313** [comment]
![Screenshot_20200422-155712506 (1)](https://user-images.githubusercontent.com/62513465/79971736-5e569880-84b2-11ea-839d-784f1d86e92e.jpg)
@Nicklas373  reported that he's having issue with video playback but I haven't faced any such issue video playback is totally fine for me on this build.

**Comment by nE0sIghT** [comment]
> @nE0sIghT, is external sdcard work on you?

Don't checked. Actually I do not using it.

**Comment by Nicklas373** [comment]
> > @nE0sIghT, is external sdcard work on you?
> 
> Don't checked. Actually I do not using it.

Ahh okay then, it's totally unmounted when i check. Not sure why, maybe need rom with 4.9 included changes

**Comment by Nicklas373** [comment]
> ![Screenshot_20200422-155712506 (1)](https://user-images.githubusercontent.com/62513465/79971736-5e569880-84b2-11ea-839d-784f1d86e92e.jpg)
> @Nicklas373 reported that he's having issue with video playback but I haven't faced any such issue video playback is totally fine for me on this build.

Yes, my panel is otm1911. Video playback not working '_'

**Comment by offset1313** [comment]
Try changing your rom

**Comment by Roker2** [comment]
> Okay i have hex edited fp blobs to make fpc work ill post a build soon and need to test sdcard

I checked it on CarbonROM Pie (without rebuilding), it didn't work.

**Comment by AryanKedare** [comment]
i m not sure but for pie since we shifted to prebuilt fp blobs on 10 
on pie we have out biometricsHAL

**Comment by Roker2** [comment]
> i m not sure but for pie since we shifted to prebuilt fp blobs on 10
> on pie we have out biometricsHAL

Does you want to say, that to need to restore biometrics HAL sources?

**Comment by AryanKedare** [comment]
> > i m not sure but for pie since we shifted to prebuilt fp blobs on 10
> > on pie we have out biometricsHAL
> 
> Does you want to say, that to need to restore biometrics HAL sources? 

fingerprint.searchf.so was modified to work with Android 10 so this blobs wont work on pie i guess 
also 

android.hardware.biometrics.fingerprint@2.1-service.xiaomi_mido  was compiled as per Biometrics HAL in pie but in Q we shifted to prebuild HAL

to make that change work on pie based roms 

hex edit fingerprint.searchf.so from lineage-16.0 of zeelog

**Comment by AryanKedare** [comment]
@nE0sIghT @offset1313 u guys have telegram account?

its better to discuss on telegram by making a 4.9 specific group since here cant make a track on comments properly

**Comment by offset1313** [comment]
yeah i have tell me your's i will pm you

**Comment by nE0sIghT** [comment]
> u guys have telegram account?

Yes, it's same as nickname

**Comment by AryanKedare** [comment]
> yeah i have tell me your's i will pm you

same as github

**Comment by offset1313** [comment]
i will be working from scratch on 4.9.219 version.
will minimal patches that will fix issues as current repo mess with tissot

**Comment by nE0sIghT** [comment]
> as current repo mess with tissot

That was the point - to have one repo for tissot and mido.

@AryanKedare 
What is your vision on this? Do you want to keep mido with tissot for Lineage or split repo?

**Comment by offset1313** [comment]
> > as current repo mess with tissot
> 
> That was the point - to have one repo for tissot and mido.
> 
> @AryanKedare
> What is your vision on this? Do you want to keep mido with tissot for Lineage or split repo?

no you should keep going with this repo
i will  try patches on upstream first and confirm

**Comment by AryanKedare** [comment]
Anything will go 
Since i no longer maintain los

It will be good if we split it

**Comment by nE0sIghT** [comment]
> Since i no longer maintain los

That's sad

**Comment by kondors1995** [comment]
Nice work so far if you are creating tg group add me to, i cant gurantue i iwll be able to help but i willsee what can i do

**Comment by offset1313** [comment]
> Nice work so far if you are creating tg group add me to, i cant gurantue i iwll be able to help but i willsee what can i do

Telegram id ?

**Comment by herobuxx** [comment]
> > Nice work so far if you are creating tg group add me to, i cant gurantue i iwll be able to help but i willsee what can i do
> 
> Telegram id ?

@offset1313 can i join the group? Let see if i an help

**Comment by offset1313** [comment]
Is your Id @herobuxx  check pm

**Comment by kondors1995** [comment]
@NATO66613

**Comment by raphielscape** [comment]
Well, I'm interested, I fascinated about the IOMMU fix that you do, I've been working around it like 6 months and then gives up, and been 2 years since I'm working with mido, I'll see if I can help

I don't need to tell my Telegram username, I guess

**Comment by AryanKedare** [comment]
> Well, I'm interested, I fascinated about the IOMMU fix that you do, I've been working around it like 6 months and then gives up, and been 2 years since I'm working with mido, I'll see if I can help
> 
> I don't need to tell my Telegram username, I guess

Cannot be addee due to users privacy settings

**Comment by raphielscape** [comment]
> Cannot be addee due to users privacy settings

Whitelisted

**Comment by nE0sIghT** [comment]
For video decoding to work ```hardware/qcom/media``` should be built with newer headers.

**Comment by nivethjunnithan** [comment]
video playback works for me in ancient premeval

**Comment by savioruz** [comment]
If temperature high, stuck on 1400 Mhz and 1800 they can't 600MHz

**Comment by Nicklas373** [comment]
> If temperature high, stuck on 1400 Mhz and 1800 they can't 600MHz

Thermal throttling limit

**Comment by offset1313** [comment]
> If temperature high, stuck on 1400 Mhz and 1800 they can't 600MHz 

Safety feature.

**Comment by Nicklas373** [comment]
> > If temperature high, stuck on 1400 Mhz and 1800 they can't 600MHz
> 
> Safety feature.

But logically it should throttle at 1.6Ghz from thermal.conf, not sure why in here got lower limit than default

**Comment by Kiciuk** [comment]
@nE0sIghT Sorry for bumping this thread.
Im trying to get mainline kernel to run and have some issues regarding Panel/mdss Initialization.
Do you have matrix/discord/telegram account?

**Comment by nE0sIghT** [comment]
@Kiciuk
I'm nE0sIghT everywhere except WoT where my nickname was stoled by some mad girl.

**Comment by nE0sIghT** [comment]
Closing done
